describe("Test env", function()
    it("can access vim namespace", function()
        assert(vim, "Cannot access vim namespace")
        assert.are.same(vim.trim("  a "), "a")
    end)

    it("uses correct nvim version", function()
        assert(vim.version, "Cannot access vim.version namespace")
        assert(vim.version.gt, "Cannot access newer vim.version namespace")
        local curr = vim.version()
        local min = require("bartbie.health").MINIMAL_VERSION
        local needed = vim.version.parse(min)
        assert(curr >= needed, tostring(curr) .. " found; " .. min .. " needed")
    end)

    it("can access vim.list namespace", function()
        assert(vim.list, "Cannot access vim.list namespace")
        assert.are.same(vim.list.unique({ 1, 1, 2, 2, 3 }), { 1, 2, 3 })
    end)
    -- it("Test can access nvim-nio dependency", function()
    --     assert(require("nio"), "Could not access plenary")
    -- end)
    it("can access module in lua/bartbie", function()
        assert(require("bartbie.symbols"), "Could not access main module")
    end)

    it("vim.env.VIMRUNTIME exists", function()
        assert.no.Nil(vim.env.VIMRUNTIME)
    end)
end)
