return {
    diagnostics_symbols = {
        core = {
            error = "",
            warn = "",
            hint = "",
            info = "",
        },
        rest = {
            other = "✓",
            action = "",
            bug = "",
        },
    },
    cmp_icons = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
    },
    special_types = {
        filetypes = {
            "neo-tree",
            "lazy",
            "mason",
            "dbui",
            "fugitive",
            "gitcommit",
            "fugitiveblame",
            "Trouble",
            "TelescopePrompt",
            "alpha",
            -- "NvimTree",
            -- "packer",
            -- "startify",
        },
        buftypes = {},
        bufnames = {},
    },
}
