name: format
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:
  format:
    runs-on: ubuntu 20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Apply Stylua
        uses: JohnnyMorganz/stylua-action@2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=.stylua.toml lua/
          version: latest

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "chore: formatting"
          branch: ${{ github.head_ref }}
          file_pattern: lua/
